services:
  postgres:
    image: postgres:16
    container_name: fotomandalin_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fotomandalin
      POSTGRES_USER: fotomandalin_user
      POSTGRES_PASSWORD: fotomandalin
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fotomandalin_user -d fotomandalin"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: development
    container_name: fotomandalin_web
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://fotomandalin_user:fotomandalin@postgres:5432/fotomandalin
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - nextjs_cache:/app/.next
    depends_on:
      - postgres

volumes:
  pgdata:
  nextjs_cache: